title: KS1StorytellingTraining_Session2_GBICi1b
hero_image: images/banner.png
description: KS1 Storytelling Training, Session2, Part1 for GBICi1b research project
version: 4
listed: false
copyedit: false
last_tested: "2020-09-08"
steps:
  - title: Accessing the Storytelling resources
  - title: The resources
  - title: Overview
  - title: "Task 1: Technical set-up for trial"
  - title: "Task 2: What's ScratchJr?"
  - title: Lesson Plans and Presentation Slides
