title: KS1 Storytelling Training, Session 2, Part 1, GBICi1b
hero_image: images/banner.png
description: Session 2 of training for teachers introduces the remainder of the resources for KS1 Storytelling GBICi1b trial through a series of tasks
version: 4
listed: false
copyedit: false
last_tested: "2020-09-08"
steps:
  - title: Accessing the Storytelling resources
  - title: The resources
  - title: Overview
  - title: "Task 1: Technical set-up for trial"
  - title: "Task 2: What's ScratchJr?"
  - title: Lesson Plans and Presentation Slides
