---
title: 'Session 2: KS1 ''Storytelling'' training – Getting started'
hero_image: images/introduction2.png
description: Session 2 of the online training course introduces teachers to setting
  up for the KS1 'Storytelling' Teaching Approach trial through a series of tasks
version: 4
listed: false
copyedit: false
last_tested: '2020-09-08'
steps:
- title: Accessing the 'Storytelling' resources
  completion: engaged
- title: The resources
- title: The Units overview
- title: 'Task 1: Technical setup for the project'
- title: 'Task 2: What''s ScratchJr?'
  completion: internal
- title: Lesson plans and presentation slides
